### ISSUE TITLE
chopper v0.8.0 GLIBC_2.XX not found

### ISSUE THREAD

**Issue by mlhoggard** [wdecoster/chopper#36]
Hi there,

I'm just trying out the latest version of chopper (v0.8.0/chopper-linux.zip), but I'm getting same GLIBC error that's been mentioned in previous issues (e.g. #28). 

The previous issue seems to be resolved with the musl build. Is there a musl build available for v0.8.0? Or is there an alternative fix?

Example error output:

``chopper: /lib64/libc.so.6: version `GLIBC_2.28' not found (required by chopper)``

Cheers!
Mike.

**Comment by wdecoster** [comment]
Hi Mike,

Yes, that problem is indeed solved by the musl build. I need to make a new 0.9.0 release soon, and will include a musl build with that. Alternatively, you can use one from an older version.

Best,
Wouter

**Comment by mlhoggard** [comment]
Hi Wouter,

That makes sense thanks. We're in the prelim stages with this data at the moment, so I'll make use of an older version in the meantime, and will keep an eye out for the 0.9.0 release.

And thanks for your work on all these tools in general. I'm just dipping more into Nanopore data and several of your tools have been very useful thanks!

Cheers,
Mike.

**Comment by AnupamGautam** [comment]
Dear @wdecoster ,  

Would it be possible to create a musl build for version 0.9.0? I am still encountering the following error, and the version on Conda is still 0.8.0:  

```
./chopper: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.28' not found (required by ./chopper)
```

Thank you for your help.  

Best regards,  
Anupam

**Comment by wdecoster** [comment]
Hi @AnupamGautam,

It appears to me conda should have v0.9.0? https://bioconda.github.io/recipes/chopper/README.html
For some reason I fail to create a musl build right now, and I won't have time to investigate this soon.
Let me know if conda doesn't solve this for you, and I can help you build it from source.

Best,
Wouter

**Comment by AnupamGautam** [comment]
Dear Wouter,  

I reinstalled Chopper via Conda. While the Conda package version indicates 0.9.0 during installation, the help output (`chopper -V`) still shows 0.8.0:  

```bash
(choppernew) ubuntu@second:~$ conda install -c bioconda -c conda-forge chopper
...
The following NEW packages will be INSTALLED:
  chopper            bioconda/linux-64::chopper-0.9.0-hdcf5f25_1
...
(choppernew) ubuntu@second:~$ chopper -V
chopper 0.8.0
```

I checked the `Cargo.toml` file in the source archive (`https://github.com/wdecoster/chopper/archive/v{{ version }}.tar.gz`) defined in the `meta.yaml` file, and it still specifies version 0.8.0. This seems to confirm that the version discrepancy arises from the `Cargo.toml`.  

Could you confirm if this is the case, and whether the installed version is indeed 0.9.0 despite the output showing 0.8.0?  

Thank you for your time and assistance!  

Best regards,  
Anupam
